### PR TITLE
Ember 1.11

### PR DESCRIPTION
**Pull request by iezer**
@bantic For you, fix using Ember.View.views as you suggested.

### CODE REVIEW

**Comment by bantic** [comment]
@iezer a test failure. I imagine that `Ember.View.views` lists all views, whether they are on the page or not, so it's erroneously reporting true for a component that is in memory (in Ember.View.views) but not shown on the page. I think that's why this test is failing.

**Comment by iezer** [comment]
@bantic That issue was actually because I fixed what I thought was a typo `tehre` -> `there`. Happy to add another test but what's the best way to add a view that is not on the page? would it work to add a component and set `display: none` in CSS, or put the component in an `if` block that flips from true to false?

**Comment by bantic** [comment]
@iezer Yeah, adding another route to the dummy app would be the easiest way to do this. Move most of what is in the [dummy application.hbs](https://github.com/201-created/ember-cli-acceptance-test-helpers/blob/master/tests/dummy/app/templates/application.hbs) into an `index.hbs` file, then add another route to the [dummy router](https://github.com/201-created/ember-cli-acceptance-test-helpers/blob/master/tests/dummy/app/router.js) that does not have that component and confirm that the appropriate test passes there

**Comment by bantic** [comment]
and add an `{{outlet}}` to application.hbs

**Comment by bantic** [comment]
@iezer boo-yah!

**Pull request merged**
