### PR TITLE
Fixes compatibility issues with ember 2.9 and 2.13

### PR DESCRIPTION
**Pull request by jelhan**
This PR fixes compatibilty issues with ember 2.9 (#34) and 2.13 (#36). It also upgrades ember to current LTS (2.12).

# Global assertions dropped in QUnit 2.0 (ember 2.9)
ember-cli has updated to QUnit 2.0 in it's 2.9.0 release.

QUnit 2.0 has dropped global assertions.
Therefore tests are throwing if ember-cli-qunit 3.0 is used, which is
included in ember-cli since 2.9.0 release.

To drop global assertions we have to pass assert to test helper as suggested
by examples in ember guide:
https://guides.emberjs.com/v2.10.0/testing/acceptance/#toc_custom-test-helpers

This is a breaking change. E.q.
  `expectComponent(componentName, count, options)`
has to be changed to
  `expectComponent(assert, componentName, count, options)`

Please note that this might not be the public api in long term. Discussion is ongoing in #34.

# _lookupFactory is removed in 2.13
The private API method `_lookupFactory` is removed in 2.13. This PR uses `factoryFor` if possible.

### CODE REVIEW

**Comment by jelhan** [comment]
@bantic @iezer Any chance to get this one merged? Is this project still alive?

**Comment by iezer** [comment]
@jelhan Thanks again for your contribution and continued interest in this addon. As discussed in #34, I'm not crazy about adding this requirement to pass `assert` as a parameter to every invocation of `expectComponent` and `expectElement`.  You seemed to like my suggestion that we use the syntax `assert.hasComponent` and `assert.hasElement`. If you have time to implement that solution I'd be happy to help and get it merged.

Merging this PR would require a major version bump and that we support two versions, which is something that I'd prefer to avoid.

**Comment by jamesarosen** [comment]
+1 for `assert.hasComponent` and `assert.hasElement`.

**Comment by jamesarosen** [comment]
Not sure what to do about `clickComponent`, though. `assert.clickComponent` feels weird, as does `clickComponent(assert, ...)`.

**Comment by iezer** [comment]
@jamesarosen I think that's fine. This PR already uses "Ember.assert" for `clickComponent'.

**Comment by jamesarosen** [comment]
Another thing I can't figure out is how this translates:
```js
App.testHelpers.withinElement('.some-div', function(){
  App.testHelpers.expectElement('.inner-div');
  App.testHelpers.expectNoElement('.outer-div');
});
```
How can the ember test helper `withinElement` communicate its scope to the QUnit assertion `hasElement`?

**Comment by jamesarosen** [comment]
Also: if we change to `assert.hasElement` (et al), what happens to `App.testHelpers.expectElement` (et al)?

**Comment by jelhan** [comment]
To be honest I'm only using `expectComponent` test helper. I don't see the benefit of `assert.hasElement(selector)` over `assert.ok(this.$(selector).length >= 1)` in integration test or `assert.ok(find(selector).length >= 1)` in acceptance tests. Same applies for `assert.hasNoElement(selector)` vs `assert.ok(this.$(selector).length === 0)`.

I see some benefits of using `withinElement` for scoping.

```
withinElement(selector, () => {
  assert.hasElement(another-selector);
});
```

is more readable than

```
$scope = this.$(selector);
assert.ok(this.$(another-selector, scope).length >=1);
```

but the last one is way more flexible since selector could be passed to any jQuery function and not only the test helpers provided here. But since I'm using ember-cli-page-object more and more even `exceptComponent` becomes less important for me. I used expectComponent mostly for maintainability of tests but getting the same benefit of page-object components nowadays.

So to put it all together: I'm not quite sure if I'm willing to put much time into this addon. But since some of my projects still relies on expectComponent test helper I will still maintain this PR as a work-a-round until `assert.hasComponent` or something else is implemented.

**Pull request merged**
