### PR TITLE
Count missing

### PR DESCRIPTION
**Pull request by Twinkletoes**
Fixes issues https://github.com/201-created/ember-cli-acceptance-test-helpers/issues/13 and https://github.com/201-created/ember-cli-acceptance-test-helpers/issues/14

### CODE REVIEW

**Comment by Twinkletoes** [comment]
Exposes bug when routes are nested - each-view doesn't correctly find child views of application template

**Comment by Twinkletoes** [comment]
Fixed nested routes - a silly mistake in the test, using route instead of resource in the dummy app

**Comment by Twinkletoes** [comment]
I think this is ready to merge

**Comment by bantic** [comment]
@Twinkletoes thanks, this is great! Could you please rebase/squash your commits before I merge?

**Pull request closed without merging**
